#!/bin/sh

case "$1" in
  start)
    echo "Starting client socket"
    cd /usr/bin
    ./socket_client -E &
    
    echo "Initializing BlueZ stack"
    modprobe hci_uart
    hciattach /dev/ttyS0 bcm43xx 115200 noflow -
    hciconfig hci0 up
    /usr/libexec/bluetooth/bluetoothd -E &
    bt-adapter -l
    ;;
    
    stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
